stages:
  - init
  - validate
  - plan
  - deploy

terraform_init:
  stage: init
  script:
    - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan

deploy:
  stage: deploy
  script:
    - terraform apply